//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_CURD_TOKO_HARDWARE_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPembelian
    {
        public int IdItemPembelian { get; set; }
        public int IdPembelian { get; set; }
        public int IdAdmin { get; set; }
        public int IdBarang { get; set; }
        public int TotalHarga { get; set; }
        public int QTY { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Barang Barang { get; set; }
        public virtual Pembelian Pembelian { get; set; }
        public virtual UserAdmin UserAdmin { get; set; }
    }
}
