//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_CURD_TOKO_HARDWARE_SOFTWARE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Final_Task_WPFEntities4 : DbContext
    {
        public Final_Task_WPFEntities4()
            : base("name=Final_Task_WPFEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barang> Barang { get; set; }
        public virtual DbSet<ItemPembelian> ItemPembelian { get; set; }
        public virtual DbSet<ItemPenjualan> ItemPenjualan { get; set; }
        public virtual DbSet<Pembelian> Pembelian { get; set; }
        public virtual DbSet<Penjualan> Penjualan { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<UserAdmin> UserAdmin { get; set; }
    }
}
